spring:
  datasource:
    #    schema:
    #      - classpath:sql/department.sql
    #      - classpath:sql/employee.sql
    initialization-mode: always
    url: jdbc:mysql://10.100.116.16:3306/spring_cache
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 10.100.116.16
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8081